apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tw0d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-tw0d
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-tw0d
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tw0d
status:
  loadBalancer: {}
